### ISSUE TITLE
setAutomaticRecoveryEnabled() is applicable for argument types: (java.lang.Boolean) values: [true]

### ISSUE THREAD

**Issue by mgara** [budjb/grails-rabbitmq-native#63]
Works fine with grails run-app but not in production.
Im getting this error : 
2015-07-06 13:28:53,625 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
groovy.lang.MissingMethodException: No signature of method: com.rabbitmq.client.ConnectionFactory.setAutomaticRecoveryEnabled() is applicable for argument types: (java.lang.Boolean) values: [true]
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
    at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
...

JRE 1.8
Plugin version : 3.1.0

**Comment by budjb** [comment]
The only time I've seen this is when the wrong version of the Java rabbitmq library is being loaded.  If an older jar version is somehow  making its way onto the classpath, that property did not always exist and so you'll see this problem.  I'd advise taking a look at your loaded dependencies (grails dependency-report) and see if you can find any problems.
