### ISSUE TITLE
MissingMethodException: getParameterCount()  on Consumer

### ISSUE THREAD

**Issue by sanpraj** [budjb/grails-rabbitmq-native#82]
I am getting below exception while consuming message. It is not even going to TaskConsumer which is my consumer class.

Version using : compile "org.grails.plugins:rabbitmq-native:3.3.1"

INFO com.budjb.rabbitmq.connection.ConnectionContextImpl - connecting to RabbitMQ server 'defaultConnection' at 'localhost:5672' on virtual host '/'
ERROR com.budjb.rabbitmq.consumer.ConsumerContextImpl - unexpected exception class groovy.lang.MissingMethodException encountered in the rabbit consumer associated with handler TaskConsumer
groovy.lang.MissingMethodException: No signature of method: java.lang.reflect.Method.getParameterCount() is applicable for argument types: () values: []
Possible solutions: getParameterTypes()
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
    at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
    at

**Comment by chakas** [comment]
any luck sanpraj? becoz i am also getting the same issue.

**Comment by budjb** [comment]
Do you have a code example that will produce this?

**Comment by rafbermudez** [comment]
Maybe I can help you

If I running my application in jdk7 I have this error 
Else the same application running in jdk8 works fine

**Comment by budjb** [comment]
Closing this. Plugin is compiled with JDK8 going forward. Please reopen if this is still an issue.
