### ISSUE TITLE
java.util.concurrent.TimeoutException in com.rabbitmq.utility.BlockingCell

### ISSUE THREAD

**Issue by robertoschwald** [budjb/grails-rabbitmq-native#93]
From time to time, I get the following exception in a Soap Client when calling RabbitMessagePublisherImpl.send:

08:32:35.010 [ajp-nio-8009-exec-12] [] DEBUG org.springframework.ws.soap.server.SoapMessageDispatcher - Endpoint invocation resulted in exception - responding with Fault
java.util.concurrent.TimeoutException: null
        at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:76) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:110) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:372) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:583) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:508) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:501) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:67) ~[amqp-client-3.6.6.jar:3.6.6]
        at com.rabbitmq.client.Channel$close$14.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-2.4.5.jar:2.4.5]
        at com.budjb.rabbitmq.publisher.RabbitMessagePublisherImpl.send(RabbitMessagePublisherImpl.groovy:81) ~[rabbitmq-native-3.3.2.jar:na]

And then the thread hangs forever. I need to restart my application to get the client working again.

**Comment by robertoschwald** [comment]
Stopping the Tomcat server leads to a lot of hanging thread warnings in such state:

"ajp-nio-8009-exec-190" #1891 daemon prio=5 os_prio=0 tid=0x00007f44040c7800 nid=0x41a5 in Object.wait() [0x00007f43d04ce000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:49)
        - locked <0x00000006db0a1f78> (a com.rabbitmq.utility.BlockingValueOrException)
        at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:88)
        - locked <0x00000006db0a1f78> (a com.rabbitmq.utility.BlockingValueOrException)
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:32)
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:366)
        at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:229)
        at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:117)
        at com.rabbitmq.client.impl.ChannelN.open(ChannelN.java:114)
        at com.rabbitmq.client.impl.ChannelManager.createChannel(ChannelManager.java:143)
        at com.rabbitmq.client.impl.AMQConnection.createChannel(AMQConnection.java:517)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.createChannel(AutorecoveringConnection.java:112)
        at com.rabbitmq.client.Connection$createChannel$1.call(Unknown Source)
        at com.budjb.rabbitmq.connection.ConnectionContextImpl.createChannel(ConnectionContextImpl.groovy:149)
        at com.budjb.rabbitmq.connection.ConnectionContext$createChannel.call(Unknown Source)
        at com.budjb.rabbitmq.connection.ConnectionManagerImpl.createChannel(ConnectionManagerImpl.groovy:111)
        at com.budjb.rabbitmq.connection.ConnectionManager$createChannel.call(Unknown Source)
        at com.budjb.rabbitmq.publisher.RabbitMessagePublisherImpl.send(RabbitMessagePublisherImpl.groovy:72)
        at com.budjb.rabbitmq.publisher.RabbitMessagePublisher$send.callCurrent(Unknown Source)

**Comment by budjb** [comment]
This problem lies with the `BlockingCell` object. Everything I can find online points to a hardcoded 5 second timeout, and the RabbitMQ folks are quick to point at network issues. Given the output when Tomcat shuts down, it looks like it's the same object waiting forever.

Not sure what to do here except upgrade (or perhaps downgrade) the library version.

**Comment by robertoschwald** [comment]
Found the problem. Disk space on RMQ server was full, so it stops accepting connections
